import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground h-screen px-[50px] flex justify-center items-center">
        {children}
      </body>
    </html>
  );
}
